/**
 * Vercel build — static site only (no Next.js).
 * Optionally injects an external voice-proxy WebSocket URL for production.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");

const wsUrl = process.env.VOICE_PROXY_URL?.trim() || null;

const runtime = `// Generated by scripts/vercel-build.mjs — do not edit on Vercel
window.YUKI_RUNTIME = ${JSON.stringify({ wsUrl }, null, 2)};
`;

fs.writeFileSync(path.join(root, "js", "runtime.js"), runtime);
console.log("Vercel build OK (static Yuki app)");
if (wsUrl) console.log("Voice proxy:", wsUrl);
else console.log("Voice: set VOICE_PROXY_URL env to enable Inworld on Vercel");
