/**
 * Vercel build — inject runtime config with direct WSS URL to voice backend.
 * Vercel cannot proxy WebSocket upgrades; the browser must connect to Railway directly.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");

function httpsToWss(base) {
  if (!base) return null;
  const trimmed = base.trim().replace(/\/$/, "");
  const wsBase = trimmed.replace(/^https:/i, "wss:").replace(/^http:/i, "ws:");
  return `${wsBase}/realtime`;
}

const backend = process.env.VOICE_BACKEND_URL?.trim().replace(/\/$/, "") || null;
const wsUrl =
  process.env.VOICE_PROXY_URL?.trim() ||
  httpsToWss(backend);

const runtime = {
  wsUrl: wsUrl || null,
  voiceBackend: !!(backend || wsUrl),
  voiceBackendUrl: backend || null,
};

fs.writeFileSync(
  path.join(root, "js", "runtime.js"),
  `// Generated by scripts/vercel-build.mjs — do not edit on Vercel deploys
window.YUKI_RUNTIME = ${JSON.stringify(runtime, null, 2)};
`
);

console.log("Vercel build OK");
if (wsUrl) console.log("Voice WebSocket →", wsUrl);
else console.warn("WARNING: set VOICE_BACKEND_URL or VOICE_PROXY_URL for voice on Vercel");
